const USER_ROLES = ['CUSTOMER', 'RIDER', 'ADMIN'];
const USER_STATUSES = ['ACTIVE', 'INACTIVE', 'SUSPENDED'];

const PRODUCT_STATUSES = ['ACTIVE', 'INACTIVE', 'OUT_OF_STOCK'];

const ORDER_STATUSES = [
  'PENDING',
  'CONFIRMED',
  'PROCESSING',
  'READY_FOR_PICKUP',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'CANCELLED',
];

const PAYMENT_METHODS = ['CASH', 'CARD', 'TRANSFER'];
const PAYMENT_STATUSES = ['PENDING', 'SUCCESSFUL', 'FAILED', 'REFUNDED'];

const RIDER_AVAILABILITY = ['AVAILABLE', 'BUSY', 'OFFLINE'];
const VEHICLE_TYPES = ['BICYCLE', 'MOTORCYCLE', 'CAR', 'VAN'];

const DELIVERY_STATUSES = [
  'PENDING',
  'ASSIGNED',
  'PICKED_UP',
  'IN_TRANSIT',
  'DELIVERED',
  'CANCELLED',
];

const ORDER_TRANSITIONS = {
  PENDING: ['CONFIRMED', 'CANCELLED'],
  CONFIRMED: ['PROCESSING', 'CANCELLED'],
  PROCESSING: ['READY_FOR_PICKUP', 'CANCELLED'],
  READY_FOR_PICKUP: ['OUT_FOR_DELIVERY', 'CANCELLED'],
  OUT_FOR_DELIVERY: ['DELIVERED'],
  DELIVERED: [],
  CANCELLED: [],
};

const DELIVERY_TRANSITIONS = {
  PENDING: ['ASSIGNED', 'CANCELLED'],
  ASSIGNED: ['PICKED_UP', 'CANCELLED'],
  PICKED_UP: ['IN_TRANSIT', 'CANCELLED'],
  IN_TRANSIT: ['DELIVERED'],
  DELIVERED: [],
  CANCELLED: [],
};

const PAYMENT_TRANSITIONS = {
  PENDING: ['SUCCESSFUL', 'FAILED'],
  SUCCESSFUL: ['REFUNDED'],
  FAILED: [],
  REFUNDED: [],
};

const CUSTOMER_CANCELABLE_STATUSES = ['PENDING', 'CONFIRMED'];

const DELIVERY_STATUSES_CANCELABLE = ['PENDING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT'];

module.exports = {
  USER_ROLES,
  USER_STATUSES,
  PRODUCT_STATUSES,
  ORDER_STATUSES,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
  RIDER_AVAILABILITY,
  VEHICLE_TYPES,
  DELIVERY_STATUSES,
  ORDER_TRANSITIONS,
  DELIVERY_TRANSITIONS,
  PAYMENT_TRANSITIONS,
  CUSTOMER_CANCELABLE_STATUSES,
  DELIVERY_STATUSES_CANCELABLE,
};
